In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [10]:
data_folder = '../data/'
df_events = pd.read_pickle(data_folder+'1x/events/2023.06.23.pkl')

In [13]:
df_tables = pd.read_pickle('C:/projects/betting/bets_project/data/1x/tables/2023.06.23/0.pkl')

In [14]:
df_tables

,Дата-время скана линии,П1,П2,1Х,2Х,Х,12,ТМ,ТМ бол,ТМ мен,...,Коэф Ф1,ФОРА 2,Коэф Ф2,Инд ТОТ 1,ИТ1 бол,ИТ1 мен,Инд ТОТ 2,ИТ2 бол,ИТ2 мен,Прим.
0,22 июн 22:20,"2,65","1,48",,,,,"22,5","1,83","1,97",...,"1,97","-2,5","1,83",,,,,,,
1,22 июн 22:30,"2,83","1,43",,,,,"22,5","1,83","1,97",...,"2,07","-2,5","1,75",,,,,,,
2,22 июн 22:40,3,"1,39",,,,,"22,5","1,83","1,97",...,"1,74","-3,5","2,09",,,,,,,
3,22 июн 23:00,"3,05","1,38",,,,,"22,5","1,85","1,95",...,"1,76","-3,5","2,06",,,,,,,
4,23 июн 00:00,"3,15","1,36",,,,,"22,5","1,85","1,95",...,"1,78","-3,5","2,03",,,,,,,
5,23 июн 00:50,"3,14","1,36",,,,,"22,5","1,83","1,97",...,"1,76","-3,5","2,06",,,,,,,
6,23 июн 04:10,3,"1,39",,,,,"22,5","1,82","1,99",...,"1,73","-3,5","2,1",,,,,,,
7,23 июн 05:30,"3,32","1,33",,,,,"22,5","1,84","1,96",...,"1,8","-3,5","2,01",,,,,,,
8,23 июн 05:40,"3,32","1,33",,,,,"22,5","1,86","1,94",...,"1,8","-3,5","2,01",,,,,,,
9,23 июн 06:50,"3,4","1,32",,,,,"22,5","1,86","1,94",...,"1,82","-3,5","1,98",,,,,,,
10,23 июн 07:10,"3,26","1,34",,,,,"22,5","1,85","1,95",...,"1,78","-3,5","2,03",,,,,,,
11,23 июн 07:40,"3,32","1,33",,,,,"22,5","1,85","1,95",...,"1,8","-3,5","2,01",,,,,,,
12,23 июн 08:10,"3,4","1,32",,,,,"22,5","1,85","1,95",...,"1,81","-3,5",2,,,,,,,
13,23 июн 09:20,"3,46","1,31",,,,,"22,5","1,85","1,95",...,"1,82","-3,5","1,98",,,,,,,
14,23 июн 09:40,"3,54","1,3",,,,,"22,5","1,87","1,93",...,"1,84","-3,5","1,96",,,,,,,
15,23 июн 10:10,"3,32","1,33",,,,,"22,5","1,85","1,95",...,"1,79","-3,5","2,02",,,,,,,
16,23 июн 12:40,"3,46","1,31",,,,,"22,5","1,83","1,97",...,"1,8","-3,5","2,01",,,,,,,
17,23 июн 13:00,"3,4","1,32",,,,,"22,5","1,81",2,...,"1,77","-3,5","2,05",,,,,,,

In [12]:
df_events

,date,event,players,winner,score
0,23.06.2023 13:00,Теннис : ATP. Галле,Александр Бублик - Янник Синнер,,
1,23.06.2023 14:30,Теннис : ATP. Галле,Александр Зверев - Николас Харри,Победа: Александр Зверев,"Счет: 2:0 (7:5,6:3)"
2,23.06.2023 17:15,Теннис : ATP. Галле,Даниил Медведев - Роберто Баутиста-Агут,Победа: Роберто Баутиста-Агут,"Счет: 0:2 (5:7,6:7)"
3,23.06.2023 19:15,Теннис : ATP. Галле,Андрей Рублёв - Таллон Грикспур,Победа: Андрей Рублёв,"Счет: 2:1 (3:6,6:3,6:4)"
4,23.06.2023 14:05,Теннис : ATP. Галле. Пары,Аревало-Гонзалес/Ройер - Отте/Штруфф,Победа: Отте/Штруфф,"Счет: 1:2 (4:6,7:5,7:10)"
...,...,...,...,...,...
1273,23.06.2023 19:15,Теннис : Теннис. Турнир ITF. Доминиканская Рес...,М.Эрасо Гонсалес - Я.Колодинска,Победа: Я.Колодинска,"Счет: 0:2 (3:6, 0:6)"
1274,23.06.2023 16:30,Теннис : Теннис. Турнир ITF. Доминиканская Рес...,Д.Ван Емберг - Л.Драксл,Победа: Л.Драксл,"Счет: 0:2 (3:6, 4:6)"
1275,23.06.2023 16:30,Теннис : Теннис. Турнир ITF. Доминиканская Рес...,Д.Кинг - Д.Лападат,Победа: Д.Кинг,"Счет: 2:0 (6:1, 6:2)"
1276,23.06.2023 16:30,Теннис : Теннис. Турнир ITF. Доминиканская Рес...,Ж.Булаис - Т.Браунинг,Победа: Т.Браунинг,"Счет: 1:2 (6:4, 3:6, 4:6)"
1277,23.06.2023 18:30,Теннис : Теннис. Турнир ITF. Доминиканская Рес...,Д.Нуньес - Т.Стис,Победа: Д.Нуньес,"Счет: 2:1 (3:6, 6:2, 6:4)"